### ISSUE TITLE
error: post failed when trying to retrieve input balance.

### ISSUE THREAD

**Issue by Ableenk** [ovrclk/net#310]
I'm trying to call balance with this string:

`akash --node "$AKASH_NODE" query bank balances "$ACCOUNT_ADDRESS" --chain-id "akash-edgenet-1"`

But once in blue moon receive this error:

`Error: post failed: Post "http://rpc-edgenet.akashdev.net:26657": dial tcp: lookup rpc-edgenet.akashdev.net on 127.0.0.53:53: read udp 127.0.0.1:56769->127.0.0.53:53: i/o timeout`

Expected behavior:

No error

**Comment by boz** [comment]
@Ableenk , you are having a problem connecting to your DNS server - it has nothing to do with Akash.
