### ISSUE TITLE
[mainnet] seeds & persistent_peers need to be refreshed & extended

### ISSUE THREAD

**Issue by andy108369** [ovrclk/net#469]
akash 0.16.4

- all 3 seeds are offline;
- RPC could not start with the current persistent_peers;
- have successfully used Polkachu's live peers from https://www.polkachu.com/live_peers/akash - we should probably update our peers with those from their list;

**Comment by boz** [comment]
we should probably make a periodic/cron gh action that syncs the list with polkachu

**Comment by andy108369** [comment]
@sacreman maybe even worth having something that would alert us in the alert slack channel whenever some peers are offline for longer than 24 hours, WDYT?

**Comment by andy108369** [comment]
resolved by https://github.com/ovrclk/net/pull/471
followed-up by https://github.com/ovrclk/engineering/issues/375
